server:
  port: 8081

spring:
  # 注册数据源
  datasource:
    # 指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///dubbo-test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  # 连接Redis服务器
  redis:
    #host: localhost
    #port: 6379
    #password: 123456
    cluster:
      nodes: localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005

  # 配置缓存
  cache:
    type: redis                   # 指定缓存类型
    cache-names: realTimeCache    # 指定缓存区域名称

mybatis:
  # 注册mybatis中实体类的别名
  type-aliases-package: top.kwseeker.dubbo.msa.common.entity
  # 注册映射文件
  mapper-locations: classpath:top/kwseeker/dubbo/msa/msauserprovider/dao/*.xml
dubbo:
  application:
    name: msa-user-provider               #dubbo应用的名称
  registry:
    address: zookeeper://localhost:2184   #注册中心的地址
    #registry: zookeeper://zkOS1:2181?backup=zkOS2:2181,zkOS3:2181
  monitor:
    protocol: registry                    #通过注册中心发现监控中心
  protocols:
    dubbo:
      name: dubbo
      port: 20880
    rmi:
      name: rmi
      port: 1099
#    rest:
#      name: rest
#      port: 8888
